version: "3.2"
services:

  redis_pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation-image
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - python
      - /src/app/entrypoints/redis_event_consumer.py

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis_pubsub
    env_file: .env
    volumes:
      - ./src:/src
      - ./tests:/tests
    command: poetry run uvicorn src.app.entrypoints.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  pg: