apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: {{ .Values.Namespace }}
  labels:
    app: post-service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.postService.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: "{{ .Values.postService.image }}"
          env:
            - name: APP_NAME
              value: {{ .Chart.Name }}
          envFrom:
            - secretRef:
                name: post-service-secret
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: {{ .Values.postService.containerPort }}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
  labels:
    app: post-service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: post-service
  type: {{ .Values.postService.service.type }}
  ports:
    - port: {{ .Values.postService.service.port }}
      targetPort: {{ .Values.postService.service.port }}
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: post-service
  labels:
    app: post-service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: {{ .Values.Host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: post-service
                port:
                  number: {{ .Values.postService.service.port }}
  tls:
    - hosts:
        - chart-example.local
      secretName: chart-example-tls
