{{ if .Values.postService.enabled }}
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: post-service
#   labels:
#     app: post-service
#     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#     release: "{{ .Release.Name }}"
#     heritage: "{{ .Release.Service }}"
# spec:
#   replicas: {{ .Values.postService.replicas }}
#   revisionHistoryLimit: 3
#   selector:
#     matchLabels:
#       app: {{ .Chart.Name }}
#   template:
#     metadata:
#       labels:
#         app: {{ .Chart.Name }}
#     spec:
#       containers:
#         - name: {{ .Chart.Name }}
#           image: "{{ .Values.postService.image }}"
#           env: []
#           envFrom:
#             - secretRef:
#                 name: post-service-secret
#             - secretRef:
#                 name: postgres-secret
#           ports:
#             - name: http
#               containerPort: {{ .Values.postService.containerPort }}
#               protocol: TCP
# ---
# apiVersion: apps/v1
# kind: Service
# metadata:
#   name: post-service
#   labels:
#     app: post-service
#     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#     release: "{{ .Release.Name }}"
#     heritage: "{{ .Release.Service }}"
# spec:
#   type: {{ .Values.postService.service.type }}
#   ports:
#     - port: {{ .Values.postService.service.port }}
#       targetPort: http
#       protocol: TCP
#   selector:
#     app: {{ .Chart.Name }}
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: postgres
#   labels:
#     app: postgres
#     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#     release: "{{ .Release.Name }}"
#     heritage: "{{ .Release.Service }}"
# spec:
#   serviceName: postgres
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#         - name: postgres
#           image: postgres
#           env:
#             - name: POSTGRES_USER
#               value: admin
#             - name: POSTGRES_PASSWORD
#               value: y9wb3N0Z3
#             - name: POSTGRES_DB
#               value: db
#           ports:
#             - name: postgres
#               containerPort: 5432
#               protocol: TCP
#           volumeMounts:
#             - name: pg
#               mountPath: /var/lib/postgresql/data
#   volumeClaimTemplates:
#     - metadata:
#         name: pg
#       spec:
#         accessModes: [ "ReadWriteOnce" ]
#         resources:
#           requests:
#             storage: 1Gi
# ---
# apiVersion: apps/v1
# kind: Service
# metadata:
#   name: postgres
#   labels:
#     app: postgres
#     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#     release: "{{ .Release.Name }}"
#     heritage: "{{ .Release.Service }}"
# spec:
#   ports:
#     - port: 5432
#       targetPort: postgres
#       protocol: TCP
#   selector:
#     app: postgres
---
apiVersion: apps/v1
kind: Secret
metadata:
  name: post-service-secret
  labels:
    app: post-service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  API_VERSION: {{ .Chart.AppVersion | b64enc }}
---
apiVersion: apps/v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: eTl3YjNOMFoz
  POSTGRES_DB: ZGI=
  POSTGRES_URI: cG9zdGdyZXNxbDovL2FkbWluOnk5d2IzTjBaM0Bwb3N0Z3Jlczo1NDMyL2Ri
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: post-service-ingress
#   labels:
#     app: post-service
#     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#     release: "{{ .Release.Name }}"
#     heritage: "{{ .Release.Service }}"
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     kubernetes.io/tls-acme: "true"
# spec:
#   rules:
#     - host: post-service.local
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: post-service
#                 port:
#                   number: 8000
#   tls:
#     - hosts:
#         - chart-example.local
#       secretName: chart-example-tls
{{ end }}
